# Generated by Django 5.2.6 on 2025-10-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userempresa',
            old_name='texto_tamaño',
            new_name='texto_tamano',
        ),
    ]
