# Generated by Django 5.2.6 on 2025-10-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userempresa',
            name='texto_tamaño',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userempresa',
            name='texto_tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
