# Generated by Django 5.2.6 on 2025-10-15 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_userempresa_texto_tamaño_userempresa_texto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('user_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='empresa.userempresa')),
            ],
            options={
                'db_table': 'favorito',
            },
        ),
    ]
