from ..models import PlantillaClase

def run():
    
    clase_cuenta_data = [
        # Nivel 1
        {"codigo": 1, "nombre": "ACTIVO"},
        {"codigo": 2, "nombre": "PASIVO"},
        {"codigo": 3, "nombre": "PATRIMONIO"},
        {"codigo": 4, "nombre": "INGRESOS"},
        {"codigo": 5, "nombre": "EGRESOS"},
        {"codigo": 6, "nombre": "CUENTAS DE ORDEN"},

        # Nivel 2
        {"codigo": 11, "nombre": "ACTIVO CORRIENTE"},
        {"codigo": 12, "nombre": "ACTIVO NO CORRIENTE"},
        {"codigo": 21, "nombre": "PASIVO CORRIENTE"},
        {"codigo": 22, "nombre": "PASIVO NO CORRIENTE"},
        {"codigo": 31, "nombre": "CAPITAL SOCIAL"},
        {"codigo": 32, "nombre": "RESERVAS"},
        {"codigo": 33, "nombre": "RESULTADOS ACUMULADOS"},
        {"codigo": 34, "nombre": "RESULTADO DEL EJERCICIO"},
        {"codigo": 41, "nombre": "INGRESOS OPERATIVOS"},
        {"codigo": 42, "nombre": "INGRESOS FINANCIEROS"},
        {"codigo": 43, "nombre": "OTROS INGRESOS"},
        {"codigo": 44, "nombre": "AJUSTES Y DIFERENCIAS DE CAMBIOS"},
        {"codigo": 51, "nombre": "COSTOSS OPERATIVOS"},
        {"codigo": 52, "nombre": "GASTOS DE ADMINISTRACIÓN"},
        {"codigo": 53, "nombre": "GASTOS DE COMERCIALIZACIÓN"},
        {"codigo": 54, "nombre": "GASTOS FINANCIEROS"},
        {"codigo": 55, "nombre": "OTROS GASTOS"},
        {"codigo": 56, "nombre": "AJUSTES Y DIFERENCIAS DE CAMBIO"},

        # Nivel 3
        {"codigo": 111, "nombre": "EFECTIVO Y EQUIVALENTES DE EFECTIVO"},
        {"codigo": 112, "nombre": "EXIGIBLE DE CORTO PLAZO"},
        {"codigo": 113, "nombre": "REALIZABLE DE CORTO PLAZO"},
        {"codigo": 114, "nombre": "ACTIVOS TRANSITORIOS"},
        {"codigo": 115, "nombre": "ACTIVOS DIFERIDOS A CORTO PLAZO"},
        {"codigo": 116, "nombre": "CUENTAS FISCALES"},
        {"codigo": 121, "nombre": "EXIGIBLE A LARGO PLAZO"},
        {"codigo": 122, "nombre": "PROPIEDAD DE INVERSION"},
        {"codigo": 123, "nombre": "PROPIEDAD, PLANTA Y EQUIPO"},
        {"codigo": 124, "nombre": "DEPRESIACIÓN ACUMULADA"},
        {"codigo": 125, "nombre": "ACTIVOS BIOLOGICOS"},
        {"codigo": 126, "nombre": "INVERSIONES DE LARGO PLAZO"},
        {"codigo": 127, "nombre": "ACTIVOS TRANSITORIOS"},
        {"codigo": 128, "nombre": "OTROS ACTIVOS FINANCIEROS NO CORRIENTES"},
        {"codigo": 129, "nombre": "ACTIVO DIFERIDO A LARGO PLAZO"},
        #{"codigo": 1210, "nombre": "ACTIVOS INTANGIBLES"},
        #{"codigo": 1211, "nombre": "OTROS ACTIVOS A LARGO PLAZO"},
        {"codigo": 211, "nombre": "OBLIGACIONES FINANCIERAS A CORTO PLAZO"},
        {"codigo": 212, "nombre": "CUENTAS POR PAGAR A CORTO PLAZO"},
        {"codigo": 213, "nombre": "OBLIGACIONES SOCIALES"},
        {"codigo": 214, "nombre": "OBLIGACIONES FISCALES"},
        {"codigo": 215, "nombre": "PROVISIONES"},
        {"codigo": 216, "nombre": "PASIVO DIFERIDO A CORTO PLAZO"},
        {"codigo": 221, "nombre": "OBLIGACIONES FINANCIERAS A LARGO PLAZO"},
        {"codigo": 222, "nombre": "CUENTAS POR PAGAR A LARGO PLAZO"},
        {"codigo": 223, "nombre": "PREVISIONES"},
        {"codigo": 224, "nombre": "PASIVO DIFERIDO A LARGO PLAZO"},
        {"codigo": 311, "nombre": "CAPITAL"},
        {"codigo": 312, "nombre": "RESERVAS"},
        {"codigo": 313, "nombre": "RESULTADOS ACUMULADOS"},
        {"codigo": 314, "nombre": "RESULTADOS DEL EJERCICIO"},
        {"codigo": 411, "nombre": "INGRESOS POR VENTAS"},
        {"codigo": 421, "nombre": "INGRESOS FINANCIEROS"},
        {"codigo": 431, "nombre": "OTROS INGRESOS"},
        {"codigo": 432, "nombre": "OTROS INGRESOS FINANCIEROS"},
        {"codigo": 441, "nombre": "AJUSTES Y DIFERENCIAS DE CAMBIOS"},
        {"codigo": 511, "nombre": "COSTO DE VENTAS"},
        {"codigo": 512, "nombre": "COSTO DE PRODUCCION"},
        {"codigo": 513, "nombre": "DEVOLUCIONES, DESCUENTOS Y REBAJAS CONCEDIDAS"},
        {"codigo": 514, "nombre": "MERMAS Y FALLAS EN EXISTENCIAS"},
        {"codigo": 521, "nombre": "REMUNERACIONES"},
        {"codigo": 522, "nombre": "GASTOS GENERALES DE OFICINA"},
        {"codigo": 523, "nombre": "SERVICIOS ESPECIALIZADOS"},
        {"codigo": 524, "nombre": "DEPRECIACIONES, BIENES DE USO Y AMORTIZACIONES"},
        {"codigo": 525, "nombre": "IMPUESTOS, TASAS Y PATENTES"},
        {"codigo": 526, "nombre": "OTROS GASTOS DE ADMINISTRACIÓN"},
        {"codigo": 531, "nombre": "REMUNERACIONES"},
        {"codigo": 532, "nombre": "GASTOS OPERACIONALES"},
        {"codigo": 533, "nombre": "PUBLICIDAD, MARKETING Y PROPAGANDA"},
        {"codigo": 534, "nombre": "SERVICIOS ESPECIALIZADOS"},
        {"codigo": 535, "nombre": "DEPRECIACIONES, BIENES DE USO Y AMORTIZACIONES"},
        {"codigo": 536, "nombre": "OTROS GASTOS"},
        {"codigo": 541, "nombre": "GASTOS BANCARIOS"},
        {"codigo": 551, "nombre": "OTROS GASTOS"},
        {"codigo": 561, "nombre": "AJUSTES Y DIFERENCIAS DE CAMBIO"},
        
    ]

    for data in clase_cuenta_data:
        PlantillaClase.objects.get_or_create(codigo=data["codigo"],
            defaults={"nombre": data["nombre"],
                      })

